Algoritmo "semnome"

Var


     x1 , x2  : inteiro
     

Inicio


       escreval("Digite o primeiro número : ")
       leia(x1)
       
       escreval("Digite o segundo número : ")
       leia(x2)
       
       se  (x1 %  x2 = 0) ou ( x2 % x1= 0) entao
           escreva("São multiplos!")
       senao
            escreval("Não são multiplos!")
       fimse
       

       
       
       
       
Fimalgoritmo